// Generated by CoffeeScript 1.6.3
(function() {
    var createKarmaFileList, fs, run, runKarma, runPhantomjs, utils;

    fs = require('fs');

    utils = require('./utils');

    run = function(apps, options) {
        if (options == null) {
            options = {};
        }
        return runKarma(apps, options);
    };

    runPhantomjs = function(apps, options) {
        if (options == null) {
            options = {};
        }
    };

    runKarma = function(apps, options) {
        var testConfig;
        if (options == null) {
            options = {};
        }
        testConfig = fs.existsSync(options.config) && fs.realpathSync(options.config);
        testConfig || (testConfig = {
            singleRun: options.singleRun || true,
            basePath: options.basePath,
            reporters: ['progress'],
            logLevel: 'info',
            frameworks: ['jasmine'],
            browsers: options.browser && options.browser.split(/[ ,]+/) || ['PhantomJS'],
            files: createKarmaFileList(apps)
        });
        return require('karma').server.start(testConfig);
    };

    createKarmaFileList = function(apps) {
        var res = apps.map(function(app) {
            if (app.packages && app.packages.test && app.packages.test.target) {
                return app.packages.test.target.toString();
            }
        });

        return res;
    };

    module.exports.run = run;
}).call(this);
